// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWrNT1fD-GXfQUplmLBNbOCe2FxN7U6t8',
    appId: '1:1071624467206:web:c1ac0744d1747072902487',
    messagingSenderId: '1071624467206',
    projectId: 'math-flutter-backend',
    authDomain: 'math-flutter-backend.firebaseapp.com',
    databaseURL: 'https://math-flutter-backend-default-rtdb.firebaseio.com',
    storageBucket: 'math-flutter-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcy1y1Wft23740MDhGaM549iBUff6yYrc',
    appId: '1:1071624467206:android:5857b7e5101dfaf7902487',
    messagingSenderId: '1071624467206',
    projectId: 'math-flutter-backend',
    databaseURL: 'https://math-flutter-backend-default-rtdb.firebaseio.com',
    storageBucket: 'math-flutter-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNjIZOMss5whHuHpaZSC5BE9UQ11siXVQ',
    appId: '1:1071624467206:ios:e53fcf5a3bcf16e9902487',
    messagingSenderId: '1071624467206',
    projectId: 'math-flutter-backend',
    databaseURL: 'https://math-flutter-backend-default-rtdb.firebaseio.com',
    storageBucket: 'math-flutter-backend.firebasestorage.app',
    iosBundleId: 'com.example.mathGameFlutterRebuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNjIZOMss5whHuHpaZSC5BE9UQ11siXVQ',
    appId: '1:1071624467206:ios:e53fcf5a3bcf16e9902487',
    messagingSenderId: '1071624467206',
    projectId: 'math-flutter-backend',
    databaseURL: 'https://math-flutter-backend-default-rtdb.firebaseio.com',
    storageBucket: 'math-flutter-backend.firebasestorage.app',
    iosBundleId: 'com.example.mathGameFlutterRebuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWrNT1fD-GXfQUplmLBNbOCe2FxN7U6t8',
    appId: '1:1071624467206:web:13aebcff12030086902487',
    messagingSenderId: '1071624467206',
    projectId: 'math-flutter-backend',
    authDomain: 'math-flutter-backend.firebaseapp.com',
    databaseURL: 'https://math-flutter-backend-default-rtdb.firebaseio.com',
    storageBucket: 'math-flutter-backend.firebasestorage.app',
  );
}
